name: Update Stock Data

on:
  schedule:
    # Run Mon–Fri at 23:00 UTC (after US market close + buffer)
    - cron: '0 23 * * 1-5'
  workflow_dispatch: # allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance

      - name: Fetch stock data
        run: python fetch_data.py

      - name: Commit and push data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --staged --quiet || git commit -m "chore: update stock data $(date -u +%Y-%m-%d)"
          git push
